<?php

return [
    'host' => 'example.org',
    'base_url' => 'https://example.org',
    'data_dir' => dirname(__DIR__) . '/data',
    'software_name' => 'Uanna',
    'software_version' => '0.1.0',
    'community_mode' => 'closed',
    'allow_public_signup' => false,
    'expose_social_graph' => false,
    'delivery_enabled' => true,
    'delivery_timeout_seconds' => 20,
    'delivery_max_attempts' => 8,
    'inbox_enabled' => true,
    'inbox_max_bytes' => 262144,
    'inbox_max_clock_skew_seconds' => 43200,
    'timeline_refresh_inbox_limit' => 10,
    'timeline_page_size' => 80,
    'timeline_search_limit' => 5000,
    'opportunistic_workers_enabled' => true,
    'opportunistic_workers_cooldown_seconds' => 15,
    'opportunistic_inbox_limit' => 5,
    'opportunistic_delivery_limit' => 2,
    // Cupo por minuto para GET de objetos desde Nammu: por IP y, si firma con un actor ya
    // conocido, cupo propio más amplio. Retry-After anuncia lo que falta de la ventana.
    'nammu_global_limit' => 90,
    'nammu_path_limit' => 30,
    'nammu_signed_global_limit' => 600,
    'nammu_signed_path_limit' => 60,
    'default_locale' => 'es',
    'timezone' => 'Europe/Madrid',
    'max_attachment_bytes' => 25 * 1024 * 1024,
    'max_attachment_count' => 4,
    'default_avatar_path' => '/uanna.png',
    'public_path' => '',
    'local_actor_path' => '/u',
    'legacy_actor_paths' => [],
];
